package chapter12.exceptions.task28;

public class TestException {
    public static void main(String[] args) {

            String s = "Create in String";
            throw new KhaException(s);

    }
}
